remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Who is a more significant figure in a League of Legends team, ADC's or Midlaners?
logo: "/assets/league_logo.png"

# Introduction
In the dynamic and competitive world of multiplayer online battle arena (MOBA) games, understanding the roles and their impact on the game's outcome is crucial for players striving to improve their performance. This project, part of the DSC 80 course, delves into a comparative analysis of two pivotal roles: the Attack Damage Carry (ADC) and the Mid Laner, to determine which tends to have a more significant impact on match outcomes. My deep interest in MOBA games and their intricate game dynamics fuels this exploration, as I aim to examine factors such as kill participation, objective control, and overall team contribution. Through this project, I seek to offer insights that can guide players and teams in optimizing their strategies and role assignments to enhance their chances of victory.
